// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDdTdrn6m3ZRSZWYnwPX7i0V-lYK0U5WYc',
    appId: '1:500898513632:web:088f17a11a82931a780685',
    messagingSenderId: '500898513632',
    projectId: 'kalamachine1-9cc2b',
    authDomain: 'kalamachine1-9cc2b.firebaseapp.com',
    storageBucket: 'kalamachine1-9cc2b.firebasestorage.app',
    measurementId: 'G-0P0LZPN3G1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfymTSFInfSXfQ3IGj7-nSKW_WLFEUyFc',
    appId: '1:500898513632:android:231746187b2d0bd5780685',
    messagingSenderId: '500898513632',
    projectId: 'kalamachine1-9cc2b',
    storageBucket: 'kalamachine1-9cc2b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDx4pPtbI1gNxsq44BQbgP3d_NpcXZ7qiA',
    appId: '1:500898513632:ios:941162e77cd15904780685',
    messagingSenderId: '500898513632',
    projectId: 'kalamachine1-9cc2b',
    storageBucket: 'kalamachine1-9cc2b.firebasestorage.app',
    iosBundleId: 'com.example.potholedetect',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDx4pPtbI1gNxsq44BQbgP3d_NpcXZ7qiA',
    appId: '1:500898513632:ios:941162e77cd15904780685',
    messagingSenderId: '500898513632',
    projectId: 'kalamachine1-9cc2b',
    storageBucket: 'kalamachine1-9cc2b.firebasestorage.app',
    iosBundleId: 'com.example.potholedetect',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDdTdrn6m3ZRSZWYnwPX7i0V-lYK0U5WYc',
    appId: '1:500898513632:web:9eff0667abf89ae9780685',
    messagingSenderId: '500898513632',
    projectId: 'kalamachine1-9cc2b',
    authDomain: 'kalamachine1-9cc2b.firebaseapp.com',
    storageBucket: 'kalamachine1-9cc2b.firebasestorage.app',
    measurementId: 'G-K1G19YE19Q',
  );
}
